name: Generate Today Entry

on:
  schedule:
    # Runs daily at 00:01 Beijing time (16:01 UTC of the previous day)
    - cron: "1 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create today's entry
        id: generate
        shell: bash
        run: |
          set -euo pipefail

          python <<'PY'
          from datetime import datetime, timedelta, timezone, time
          from pathlib import Path
          import os

          tz = timezone(timedelta(hours=8))
          now = datetime.now(timezone.utc).astimezone(tz)
          today_date = now.date()

          display_date = today_date.strftime("%Y-%m-%d")
          year = today_date.strftime("%Y")
          month = today_date.strftime("%m")
          day = today_date.strftime("%d")

          target_dir = Path("content") / year / month
          target_file = target_dir / f"{day}.md"

          timestamp = datetime.combine(today_date, time(hour=0, minute=1), tzinfo=tz)
          iso_timestamp = timestamp.isoformat()

          target_dir.mkdir(parents=True, exist_ok=True)
          created = False

          if target_file.exists():
              print(f"File {target_file} already exists. Skipping creation.")
          else:
              # Avoid bare '---' lines in workflow YAML by constructing them at runtime
              lines = [
                  "-" * 3,
                  f"title: {display_date}",
                  f"date: {iso_timestamp}",
                  "draft: false",
                  "-" * 3,
                  ""
              ]
              target_file.write_text("\n".join(lines), encoding="utf-8")
              created = True
              print(f"Created {target_file}")

          # Expose outputs to subsequent steps
          output_path = os.environ.get("GITHUB_OUTPUT")
          if output_path:
              with open(output_path, "a", encoding="utf-8") as fh:
                  fh.write(f"today_date={display_date}\n")
                  fh.write(f"target_file={target_file.as_posix()}\n")
                  fh.write(f"created={str(created).lower()}\n")
          PY

      - name: Commit and push changes
        if: steps.generate.outputs.created == 'true'
        shell: bash
        run: |
          set -euo pipefail

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add content
          git commit -m "Add entry for ${{ steps.generate.outputs.today_date }}"
          git push

      - name: Report created file
        if: steps.generate.outputs.created == 'true'
        run: echo Generated file
